- hosts: jenkins
  become: true
  
  vars:
    jenkins_hostname: jenkins.local
    java_packages:
      - openjdk-11-jdk

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: geerlingguy.docker

- hosts: docker
  become: true

  vars:
    docker_hostname:  production.local

  roles:
    - role: geerlingguy.docker
